# Generated by Django 5.1.7 on 2025-12-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_videorequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
