# Generated by Django 5.2.9 on 2026-03-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DrawingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_drawings', to='myapp.user')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('name_on_card', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drawingbooking')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
